### ISSUE TITLE
Code on npm does not match the code on Github

### ISSUE THREAD

**Issue by just-boris** [davidmarkclements/events.on#1]
Hello!

NPM release contains the actual implementation of `events.once`, as expected: https://unpkg.com/events.once@2.0.2/index.js

But this repository code is somewhat different: https://github.com/davidmarkclements/events.on/blob/master/index.js

Perhaps you pushed a wrong branch/commit?

**Comment by davidmarkclements** [comment]
1. this is `events.on` you're looking for https://github.com/davidmarkclements/events.once
2. this isn't published yet - it's just a placeholder until `events.on` lands in core (https://github.com/nodejs/node/pull/27994#pullrequestreview-244586951) where it'll be updated to correspond.

**Comment by just-boris** [comment]
Correct. I have confused two repos somehow. Sorry about that 😅
